 ---
title: "練習1"
date: "2018-10-03"
output: html_document
params:
  studentID: "410773098"
  studentName: "鄭心詠"
---
存檔時，請用你的學號當延伸檔名。例如：若你的學號為41078392，則請`File->Save As...`存成Exercise1-41078392.Rmd。

## 1
引入[五大銀行一個月定存固定利率歷史月資料](https://raw.githubusercontent.com/tpemartin/github-data/master/bankdata.csv)。

```{r}
library(readr)
bankdata <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/bankdata.csv")
```

### 1.1
將**銀行**變數改成factor
```{r ans11}
as.factor(bankdata$銀行)
```

### 1.2
將年月改成西元年月
```{r ans12}
library(stringr)
x <- str_replace(bankdata$年月, "/" , "")
library(base)
y <- as.integer(x)
( y + 191100)
w <-as.Date.character(y , format = "%Y%M")
inherits(w, what = "Date") #這個格式是時間，但是不知道怎麼加分隔線，因為轉成字串後，不知道有哪個函數可以插入符號。
```

```{r}

library(stringr)
x <-str_sub(bankdata$年月,1,3)
s <-str_sub(bankdata$年月,5,6)
library(base)
y <- as.integer(x)
z <- ( y + 1911)
q <- as.character(z)
library(stringr)
a <-str_c(q,s,sep = "-")
as.Date.character(a, format = "%Y-%M") #到底為什麼加了這一行後，所有的數字都變成10-22呢？
```

## 2
Google天災地圖會發佈天災時地資訊，如[潭美颱風(Typhoon Trami)](https://google.org/crisismap/google.com/2018-trami)，但它的時間是以UTC表示，如"2018/30/09 00:00 UTC",試透過`lubridate::with_tz()`將"2018/30/09 00:00 UTC"轉成台灣時間。(Hint: 台灣tzone可用`grep("Taipei",OlsonNames(),value=TRUE)`指令查得)

```{r ans2}
library(lubridate)
x <- ydm_hm("2018/30/09 00:00")
with_tz(x, tz = "Asia/Taipei")
```


